disp(sprintf('thresholds =  '));
disp(thresholds);
disp(sprintf('distribution =  '));
disp(count);
disp(sprintf('perf = '));
disp(perf);
disp(sprintf('partition(3 1 2) =  '));
disp(partition);
disp(sprintf('partition1(1 3 2) =  '));
disp(partition1);
disp(sprintf('output(604) =  %f', output(:,604)));
disp(sprintf('answers(604) =  %d', answers(604)));
disp(sprintf('answers1(604) =  %d', answers1(604)));
disp(sprintf('answers(608) =  %d', answers(608)));
disp(sprintf('answers1(608) =  %d', answers1(608)));
